[general]
live_config_reload = true

[terminal]
shell = "/opt/homebrew/bin/fish"

[font]
size = 15.5
# size = 16.0
normal.family = "VictorMono Nerd Font"
normal.style = "SemiBold"

bold.family = "VictorMono Nerd Font"
bold.style = "Bold"

italic.family = "VictorMono Nerd Font Mono"
italic.style = "SemiBold Oblique"

bold_italic.family = "VictorMono Nerd Font Mono"
bold_italic.style = "Bold Oblique"

offset.x = 2
offset.y = 8
glyph_offset.x = 0
glyph_offset.y = 4

[keyboard]
bindings = [
  { key = "Key1", mods = "Command", chars = "\u001b1" },
  { key = "Key2", mods = "Command", chars = "\u001b2" },
  { key = "Key3", mods = "Command", chars = "\u001b3" },
  { key = "Key4", mods = "Command", chars = "\u001b4" },
  { key = "Key5", mods = "Command", chars = "\u001b5" },
  { key = "Key6", mods = "Command", chars = "\u001b6" },
  { key = "Key7", mods = "Command", chars = "\u001b7" },
  { key = "Key8", mods = "Command", chars = "\u001b8" },
  { key = "Key9", mods = "Command", chars = "\u0019" },
  { key = "Key6", mods = "Control", chars = "\u001e6\u000d" },
  { key = "c", mods = "Command", chars = "\u001b\u0063" },
  { key = "p", mods = "Command", chars = "\u001b\u0070" },
  { key = "l", mods = "Command", chars = "\u001b\u0063\u006c" },
]

[window]
padding = { x = 0, y = 0 }
decorations = "None"
dynamic_padding = true

[colors.primary]
background = "#eff1f5"
foreground = "#4c4f69"
dim_foreground = "#8c8fa1"
bright_foreground = "#4c4f69"

[colors.cursor]
text = "#eff1f5"
cursor = "#dc8a78"

[colors.vi_mode_cursor]
text = "#eff1f5"
cursor = "#7287fd"

[colors.search.matches]
foreground = "#eff1f5"
background = "#6c6f85"

[colors.search.focused_match]
foreground = "#eff1f5"
background = "#40a02b"

[colors.footer_bar]
foreground = "#eff1f5"
background = "#6c6f85"

[colors.hints.start]
foreground = "#eff1f5"
background = "#df8e1d"

[colors.hints.end]
foreground = "#eff1f5"
background = "#6c6f85"

[colors.selection]
text = "#eff1f5"
background = "#dc8a78"

[colors.normal]
black = "#bcc0cc"
red = "#d20f39"
green = "#40a02b"
yellow = "#df8e1d"
blue = "#1e66f5"
magenta = "#ea76cb"
cyan = "#179299"
white = "#5c5f77"

[colors.bright]
black = "#acb0be"
red = "#d20f39"
green = "#40a02b"
yellow = "#df8e1d"
blue = "#1e66f5"
magenta = "#ea76cb"
cyan = "#179299"
white = "#6c6f85"

[colors.dim]
black = "#bcc0cc"
red = "#d20f39"
green = "#40a02b"
yellow = "#df8e1d"
blue = "#1e66f5"
magenta = "#ea76cb"
cyan = "#179299"
white = "#5c5f77"

[[colors.indexed_colors]]
index = 16
color = "#fe640b"

[[colors.indexed_colors]]
index = 17
color = "#dc8a78"
