#!/usr/bin/env bash

# bootstrap installs things.

# load utils library
cd "$(dirname "$0")/.."
DOTFILES_ROOT=$(pwd -P)
source $DOTFILES_ROOT/script/utils

set -e

# print empty line , prettyness funcionality :)
echo ''

# check if my swiss army programs are installed and his versions
check_versions

# set the username:password for gitconfig, file not versioned obviously
setup_gitconfig

# make symlinks for each topic
install_dotfiles

# make symlinks for each subfolder topic
install_topic_subfolders 
