#!/usr/bin/env bash

info () {
    printf "\r  [ \033[00;34m..\033[0m ] $1\n"
}

user () {
    printf "\r  [ \033[0;33m??\033[0m ] $1\n"
}

success () {
    printf "\r\033[2K  [ \033[00;32mOK\033[0m ] $1\n"
}

fail () {
    printf "\r\033[2K  [\033[0;31mFAIL\033[0m] $1\n"
    echo ''
    exit
}

t_fail () {
    printf "\r\033[2K ├──▶ [\033[0;31mFAIL\033[0m] $1\n"
    echo ''
    exit
}

t_user () {
    printf "\r ├── [ \033[0;33m??\033[0m ] $1\n"
}

t_success () {
    printf "\r\033[2K   ├──› [ \033[00;32mOK\033[0m ] $1\n"
}

t_info() {
    printf "\r \033[00;34m ├─▶ \033[0m [ \033[00;34m..\033[0m ] $1\n"
}

t_title () {
    printf "\r [\033[00;34m ▼ $1 \033[0m]\n"

}

tree_info () {
    local numarg=$#
    local counter=1
    if [ $numarg -gt 0 ]
    then
        for var in "$@"; do
            if [[ $counter -eq 1 ]]
            then
                printf "\r \033[00;34m $var \033[0m\n"
            elif [[ $counter -eq $numarg ]]
            then
                printf "\r \033[00;34m └── \033[0m $var\n"
            else
                printf "\r \033[00;34m ├── \033[0m $var\n"
            fi
            ((counter+=1))
        done
    fi
}

link_file () {
    local src=$1 dst=$2

    local overwrite= backup= skip=
    local action=

    if [ -f "$dst" -o -d "$dst" -o -L "$dst" ]
    then

        if [ "$overwrite_all" == "false" ] && [ "$backup_all" == "false" ] && [ "$skip_all" == "false" ]
        then

            local currentSrc="$(readlink $dst)"

            if [ "$currentSrc" == "$src" ]
            then

                skip=true;

            else

                t_user "File already exists: $dst ($(basename "$src")), what do you want to do?\n\
                    [s]kip, [S]kip all, [o]verwrite, [O]verwrite all, [b]ackup, [B]ackup all?"
                read -n 1 action

                case "$action" in
                    o )
                        overwrite=true;;
                    O )
                        overwrite_all=true;;
                    b )
                        backup=true;;
                    B )
                        backup_all=true;;
                    s )
                        skip=true;;
                    S )
                        skip_all=true;;
                    * )
                        ;;
                esac

            fi

        fi

        overwrite=${overwrite:-$overwrite_all}
        backup=${backup:-$backup_all}
        skip=${skip:-$skip_all}

        if [ "$overwrite" == "true" ]
        then
            rm -rf "$dst"
            t_success "removed $dst"
        fi

        if [ "$backup" == "true" ]
        then
            mv "$dst" "${dst}.backup"
            t_success "moved $dst to ${dst}.backup"
        fi

        if [ "$skip" == "true" ]
        then
            t_success "skipped $src"
        fi
    fi

    if [ "$skip" != "true" ]  # "false" or empty
    then
        ln -s "$1" "$2"
        t_success "linked $1 to $2"
    fi
}


setup_files() {
    local section=$1
    if [ -d $DOTFILES_ROOT/vim/$section ]
    then
        if [ ! -d $HOME/.vim ] && [ -d $HOME/.vim/$section ]
        then
            t_info '$HOME/.vim/$section not found , creating folders'
            mkdir -p "$HOME/.vim/$section"
        fi

        local overwrite_all=false backup_all=false skip_all=false
        for src in $(find  -H $DOTFILES_ROOT/vim/$section -mindepth 1 -maxdepth 1 -type f -name '*.vim.symlink')
        do
            dst="$HOME/.vim/$section/$(basename "${src%.*}")"
            link_file "$src" "$dst"
        done
    fi
}
