#!/usr/bin/env bash

info () {
    printf "\r   $(pc "├$2─›" $lblue) [$(pc ' .. ' $cyan)] $1\n"
}

user () {
    printf "\r   $(pc "├$2─›" $lblue) [$(pc ' ? ' $yellow)] $1\n"
}

warn () {
    printf "\r   $(pc "├$2─›" $lblue) [$(pc ' ! ' $lred)] $1\n"
}

success () {
    printf "\r   $(pc "├$2─›" $lblue) [$(pc ' √ ' $green)] $1\n"
}

fail () {
    printf "\r   $(pc "├$2─›" $lblue) [$(pc ' FAIL ' $lred)] $1\n"
    echo ''
    exit
}

version () {
    if [ ! $(command -v $1) ]
    then
        printf "\r   $(pc "├─›" $lblue) [$(pc " ✗ " $red$bold)] $(pc $1 $red) ${bold}NOT installed${normal}\n"
    else
        if [ $# -eq 2 ]
        then
            # custom version finder
            local version="$($1 $2 | head -1 | grep -o -e '[0-9]\+\(\.[0-9]\+\)*' | head -1)"
        else
            local version="$($1 --version | head -1 | grep -o -e '[0-9]\+\(\.[0-9]\+\)*' | head -1)"
        fi
        printf "\r   $(pc "├─›" $lblue) [$(pc " √ " $green$bold)] $(pc "${1^^}" $lgreen) version $(pc $version $cyan)\n"
    fi
}

_start () {
    printf "\r [ $(pc "▼ $1" $lblue) ]\n"
}

_end () {
    printf "\r [ $(pc "▲ $1" $lblue) ]\n"
}

subfolder_title () {
    printf "\r   $(pc ├─› $lblue) [ $(pc $1 $lgray$uline) ] \n"
}


link_file () {
    local src=$1 dst=$2

    local overwrite= backup= skip=
    local action=

    if [ -f "$dst" -o -d "$dst" -o -L "$dst" ]
    then

        if [ "$overwrite_all" == "false" ] && [ "$backup_all" == "false" ] && [ "$skip_all" == "false" ]
        then

            local currentSrc="$(readlink $dst)"

            if [ "$currentSrc" == "$src" ]
            then

                skip=true;

            else

                user "${bold}$dst${normal} already exists, what to do?\n\
   $(pc │ $lblue)          ├─› [${bold}s${normal}]kip ──────── [${bold}S${normal}]kip all
   $(pc │ $lblue)          ├─› [${bold}o${normal}]verwrite ─── [${bold}O${normal}]verwrite all
   $(pc │ $lblue)          └─› [${bold}b${normal}]ackup ────── [${bold}B${normal}]ackup all?"
                read -n 1 action

                case "$action" in
                    o )
                        overwrite=true;;
                    O )
                        overwrite_all=true;;
                    b )
                        backup=true;;
                    B )
                        backup_all=true;;
                    s )
                        skip=true;;
                    S )
                        skip_all=true;;
                    * )
                        ;;
                esac

            fi

        fi

        overwrite=${overwrite:-$overwrite_all}
        backup=${backup:-$backup_all}
        skip=${skip:-$skip_all}

        if [ "$overwrite" == "true" ]
        then
            rm -rf "$dst"
            success "removed ${cyan}$dst${normal}" "$3"
        fi

        if [ "$backup" == "true" ]
        then
            mv "$dst" "${dst}.backup"
            success "moved   ${cyan}$dst${normal} to ${dst}.backup" "$3"
        fi

        if [ "$skip" == "true" ]
        then
            success "skipped ${cyan}$src${normal}" "$3"
        fi
    fi

    if [ "$skip" != "true" ]  # "false" or empty
    then
        ln -s "$1" "$2"
        success "linked  ${lgreen}$2${normal}" "$3"
    fi
}


rename_all_subfiles_to_symlink () {
    find . -type f ! -name '*.symlink' -exec mv '{}' '{}'.symlink \;
}

remove_all_symlink_ext_to_subfiles () {
    find . -type f -name '*.symlink' | while read NAME; do  mv "${NAME}" "${NAME%.symlink}"; done
}

subfolder_files() {
    local topic=$1
    local subfolder=$2
    if [ -d $DOTFILES_ROOT/$topic/$subfolder ]
    then
        local innerfolders=$(find $DOTFILES_ROOT/$topic -type d ! -path '*\.git*' ! -path  '*\.hg*' ! -path \
           '*\.svn*' -printf '%P\n' | sort )
       for innerfolder in $innerfolders
       do
            local dirfound=true
            if [ ! -d $HOME/.$topic/$innerfolder ]
            then
                dirfound=false
                warn "creating directory → $HOME/.$topic/$innerfolder${normal}" '──'
                mkdir -p "$HOME/.$topic/$innerfolder"
            fi

            local overwrite_all=false backup_all=false skip_all=false
            for src in $(find  -H $DOTFILES_ROOT/$topic/$innerfolder -maxdepth 1 -type f -name "*.symlink")
            do
                if $dirfound
                then
                    local child_visual_line="──"
                else
                    local child_visual_line="──────"
                fi

                dst="$HOME/.$topic/$innerfolder/$(basename "${src%.*}")"
                link_file "$src" "$dst" "$child_visual_line"
            done
       done
    fi
}

setup_gitconfig () {
  _start "start ${bold}setup gitconfig"
  if ! [ -f git/gitconfig.symlink ]
  then
    info 'setup gitconfig'

    git_credential='cache'
    if [ "$(uname -s)" == "Darwin" ]
    then
      git_credential='osxkeychain'
    fi

    user " - What is your github author ${bold}name${normal}?"
    read -p "$(printf  "\r   $(pc ├───────────› $lblue) ${uline}${lyellow}")" -e git_authorname
    printf ${normal}
    user " - What is your github author ${bold}email${normal}?"
    read -p "$(printf  "\r   $(pc ├───────────› $lblue) ${uline}${lyellow}")" -e git_authoremail
    printf ${normal}
    sed -e "s/AUTHORNAME/$git_authorname/g" -e "s/AUTHOREMAIL/$git_authoremail/g" -e "s/GIT_CREDENTIAL_HELPER/$git_credential/g" git/gitconfig.symlink.example > git/gitconfig.symlink

    success 'gitconfig'
  else
    success "gitconfig already configured \n\
   $(pc │ $lblue)          remove git/gitconfig.symlink if you want to reconfigure"
  fi
  _end "end ${bold}setup gitconfig"
  echo ''
}

install_dotfiles () {
  _start "start ${bold}installing dotfiles"

  local overwrite_all=false backup_all=false skip_all=false

  for src in $(find -H "$DOTFILES_ROOT" -maxdepth 2 -name '*.symlink')
  do
    dst="$HOME/.$(basename "${src%.*}")"
    link_file "$src" "$dst"
  done

  _end "end ${bold}installing dotfiles"
  echo ''
}

install_topic_subfolders () {
    _start "start ${bold}installing topic subfolders"

    for src in $(find -H "$DOTFILES_ROOT" -maxdepth 2 -name '*.subfolder' | sort)
    do
        source $src
    done

    _end "end ${bold}installing topic subfolders"
    echo ''
}

check_versions() {
    _start "start ${bold}checking versions${normal}"
    version 'bash'
    version 'git'
    version 'vim'
    version 'zsh'
    version 'randominventedprogram'
    version 'nvim'
    version 'tmux' '-V'
    version 'ag'
    version 'fzf'
    _end "end ${bold}checking versions${normal}"
    echo ''
}

# If we're on a Mac, let's install and setup homebrew.
if [ "$(uname -s)" = "Darwin" ]
then
  info "installing dependencies"
  if source bin/dot > /tmp/dotfiles-dot 2>&1
  then
    success "dependencies installed"
  else
    fail "error installing dependencies"
  fi
fi
